openapi: 3.0.3
info:
  title: PollPal API
  version: 1.0.0
  description: Your project description
paths:
  /api/poll/{poll_id}/answer:
    get:
      operationId: poll_answer_retrieve
      parameters:
      - in: path
        name: poll_id
        schema:
          type: integer
        required: true
      tags:
      - poll
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Answer'
          description: ''
  /api/poll/next-question:
    post:
      operationId: poll_next_question_create
      tags:
      - poll
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PollNextQuestion'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Poll'
          description: ''
  /api/poll/set-accepting-answer:
    patch:
      operationId: poll_set_accepting_answer_partial_update
      tags:
      - poll
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedPollSetAcceptingAnswers'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Poll'
          description: ''
  /api/poll/submit-response:
    put:
      operationId: poll_submit_response_update
      tags:
      - poll
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PollSubmitResponse'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
          description: ''
  /api/question/create:
    post:
      operationId: question_create_create
      description: Creates a question with the provided prompt and answers.
      tags:
      - question
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuestionCreate'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Question'
          description: ''
  /api/session/:
    get:
      operationId: session_list
      tags:
      - session
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Session'
          description: ''
    post:
      operationId: session_create
      tags:
      - session
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Session'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
          description: ''
  /api/session/{id}:
    delete:
      operationId: session_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - session
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/session/{session_id}/end:
    delete:
      operationId: session_end_destroy
      description: Deletes a Poll from a session. If there is no Poll, return 400.
        If the poll is accepting answers, return 400.
      parameters:
      - in: path
        name: session_id
        schema:
          type: integer
        required: true
      tags:
      - session
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/session/start:
    post:
      operationId: session_start_create
      description: Creates a poll for the session with the provided question and answer.
      tags:
      - session
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SessionStart'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Poll'
          description: ''
components:
  schemas:
    Answer:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        answer:
          type: string
          maxLength: 4095
        is_correct:
          type: boolean
        question:
          type: integer
      required:
      - id
      - question
    PatchedPollSetAcceptingAnswers:
      type: object
      properties:
        poll:
          type: integer
        is_accepting_answers:
          type: boolean
    Poll:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        is_accepting_answers:
          type: boolean
        session:
          type: integer
      required:
      - id
      - session
    PollNextQuestion:
      type: object
      properties:
        poll:
          type: integer
        question:
          type: integer
      required:
      - poll
      - question
    PollSubmitResponse:
      type: object
      properties:
        poll:
          type: integer
        answer:
          type: integer
      required:
      - answer
      - poll
    Question:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        prompt:
          type: string
          maxLength: 4095
        poll:
          type: integer
          nullable: true
      required:
      - id
    QuestionCreate:
      type: object
      properties:
        prompt:
          type: string
          maxLength: 4095
        answers:
          type: array
          items:
            $ref: '#/components/schemas/QuestionCreateAnswerInput'
      required:
      - answers
      - prompt
    QuestionCreateAnswerInput:
      type: object
      properties:
        answer:
          type: string
          maxLength: 4095
        is_correct:
          type: boolean
      required:
      - answer
      - is_correct
    Response:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        poll:
          type: integer
        answer:
          type: integer
      required:
      - answer
      - id
      - poll
    Session:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        label:
          type: string
          maxLength: 255
      required:
      - id
      - label
    SessionStart:
      type: object
      properties:
        session:
          type: integer
        question:
          type: integer
      required:
      - question
      - session
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
