name: Format prettier

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-npm:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - run: npx prettier . --check
